### PR TITLE
Fixing citations

### PR DESCRIPTION
**Pull request by thanharrison**
Citations should look consistent like this throughout the document:

    Source, Some Title - <somelink.com> <sup>[[Wikiless]][##]</sup> <sup>[[Archive.org]][##]</sup>

The unverified commit is due to GitHub through Sublime not working on my new machine.

### CODE REVIEW

**Comment by thanharrison** [comment]
> About [388914e](https://github.com/NobodySpecial256/thgtoa/commit/388914e43f20b166c138bb2004cd6f4042675576) : The links there are meant as introduction. For newcomers. ... As for privacytools.io removal. I don't know. I'll let the maintainer decide.

The reason I removed Privacy Tools (privacytools.io) is because they are absolutely not something I want to link to based on community opinion at Privacy Guides and Techlore. It used to be somewhat decent. Now it's just [affiliate links and FUD.](https://www.reddit.com/r/PrivacyGuides/comments/thnjjf/privacyguidesorg_considered_harmful/)
 
> About [06c4ce9](https://github.com/NobodySpecial256/thgtoa/commit/06c4ce97f445ef6293b35b45052f6b804b2dd369) : irrelevant to me since it shouldn't be there... it's absolutely not for newcomers. cf the previous comment.

Aidan has good stuff. Idk why it was even removed but, eh ... they don't seem to want to be involved even remotely, not even linked to by this project. Still think it's worth putting in there.

> About [1497e94](https://github.com/NobodySpecial256/thgtoa/commit/1497e945fcf856c9371384cd10233b5ff9539b1b) : I'm okay with space removal but I prefer to keep the ":" ... personal preference

It's useless and doesn't need to be in there, but it's not my decision, just what I've been thinking might do with being changed to improve readability and make it less clunky looking. This fix alone already improves the feel of the body of work by a lot.

A caveat is that it can't be done automatically and has to be done painstakingly which is not very fun for ... whoever is editing the document ... why was it even made to be like 

    [This is a link:][This is a link:]
        * asas
        
        * klsdfosdf
        
        * gjdghjdgh
        
        * lasikskpdfg

??

> About [099c87e](https://github.com/NobodySpecial256/thgtoa/commit/099c87ebf2d54eccbd2359a8b8ba6c142d78d094) : I prefer to keep the explanation than just a reference to the part in question. So I disagree

Okay, I can add this back in, it still fits with the style of the document.

**Comment by NobodySpecial256** [comment]
For the citations formatting change, I have 2 thoughts:

- I don't really see the need of this minor and IMO pointless formatting change. Adding a hyphen before the URL doesn't really seem like a big deal. Although this won't keep me from merging, I personally don't really see the point. Trivial formatting changes aren't really my concern.
- Some of the titles were changed and/or partially-removed. For example, an article titled `China is now blocking all encrypted HTTPS traffic that uses TLS 1.3 and ESNI` was changed to `China is now blocking all encrypted HTTPS traffic` in the citation, which is not only not the title of the article, but also a verifiably incorrect fact, as China isn't blocking *all HTTPS traffic*. We can't just go around changing and/or truncating the titles of references in our citations. This definitely is not getting merged into master.

I'm not closing this, as some of the changes can be merged. But I definitely won't be merging https://github.com/NobodySpecial256/thgtoa/commit/030be935934fa4ffdd82ef72e55156711e03ebd5 or https://github.com/NobodySpecial256/thgtoa/commit/099c87ebf2d54eccbd2359a8b8ba6c142d78d094. I'm still undecided with regard to whether I'll be merging https://github.com/NobodySpecial256/thgtoa/commit/388914e43f20b166c138bb2004cd6f4042675576.

**Comment by thanharrison** [comment]
I didn't want to go back and rebase or cherry pick because it takes too much effort just to fix an accidental oversight of the description for that link, so I removed this PR. Just too much work to go back and remove specific commits like that. Any questions can be directed to me on the Matrix space.

**Comment by NobodySpecial256** [comment]
You realize you can have git automatically revert a specific commit

**Comment by thanharrison** [comment]
If it's style changes we're trying to avoid, then I believe the word used was specifically "pointless".

So I'll keep it open and work on the commits later, maybe.

------- Original Message -------

**Pull request closed without merging**
